lang_dict = {"Alemán": "de_DE",
             "Checo": "cs_CZ",
             "Español": "es_MX",
             "Francés": "fr_FR",
             "Griego": "el_GR",
             "Húngaro": "hu_HU",
             "Inglés": "en_US",
             "Italiano": "it_IT",
             "Japonés": "jp_JP",
             "Polaco": "pl_PL",
             "Portugués": "pt_BR",
             "Rumano": "ro_RO",
             "Ruso": "ru_RU",
             "Turco": "tr_TR"
             }